# Site settings
title: Crash Robots
email: franciscosouzaacer@gmail.com
description: Web Site Time Crash Robots IFCE Juazeiro do Norte 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://crashrobots.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  rodriguesfas

# Build settings
markdown: kramdown

#
exclude: ['package.json', 'src', 'node_modules']